# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphicWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(477, 274)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nodeLine = QtWidgets.QFrame(Form)
        self.nodeLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.nodeLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.nodeLine.setObjectName("nodeLine")
        self.horizontalLayout.addWidget(self.nodeLine)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.addNodeBtn = QtWidgets.QPushButton(Form)
        self.addNodeBtn.setObjectName("addNodeBtn")
        self.verticalLayout.addWidget(self.addNodeBtn)
        self.deleteNodeBtn = QtWidgets.QPushButton(Form)
        self.deleteNodeBtn.setObjectName("deleteNodeBtn")
        self.verticalLayout.addWidget(self.deleteNodeBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.graphicsView = MyNeo4jView(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addNodeBtn.setText(_translate("Form", "增加节点"))
        self.deleteNodeBtn.setText(_translate("Form", "删除节点"))
from MyWidget import MyNeo4jView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
