# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NodeResultWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeResultWindow(object):
    def setupUi(self, NodeResultWindow):
        NodeResultWindow.setObjectName("NodeResultWindow")
        NodeResultWindow.resize(722, 300)
        self.gridLayout = QtWidgets.QGridLayout(NodeResultWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(NodeResultWindow)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.nodeResult = QtWidgets.QTableView(NodeResultWindow)
        self.nodeResult.setObjectName("nodeResult")
        self.horizontalLayout.addWidget(self.nodeResult)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(NodeResultWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.showForLabel = QtWidgets.QLabel(NodeResultWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.showForLabel.setFont(font)
        self.showForLabel.setObjectName("showForLabel")
        self.verticalLayout.addWidget(self.showForLabel)
        self.platformSortBtns = QtWidgets.QComboBox(NodeResultWindow)
        self.platformSortBtns.setObjectName("platformSortBtns")
        self.verticalLayout.addWidget(self.platformSortBtns)
        self.nameRadBtn = QtWidgets.QRadioButton(NodeResultWindow)
        self.nameRadBtn.setObjectName("nameRadBtn")
        self.verticalLayout.addWidget(self.nameRadBtn)
        self.playsRadBtn = QtWidgets.QRadioButton(NodeResultWindow)
        self.playsRadBtn.setObjectName("playsRadBtn")
        self.verticalLayout.addWidget(self.playsRadBtn)
        self.commentsRadBtn = QtWidgets.QRadioButton(NodeResultWindow)
        self.commentsRadBtn.setObjectName("commentsRadBtn")
        self.verticalLayout.addWidget(self.commentsRadBtn)
        self.durationRadBtn = QtWidgets.QRadioButton(NodeResultWindow)
        self.durationRadBtn.setObjectName("durationRadBtn")
        self.verticalLayout.addWidget(self.durationRadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(NodeResultWindow)
        QtCore.QMetaObject.connectSlotsByName(NodeResultWindow)

    def retranslateUi(self, NodeResultWindow):
        _translate = QtCore.QCoreApplication.translate
        NodeResultWindow.setWindowTitle(_translate("NodeResultWindow", "Form"))
        self.label.setText(_translate("NodeResultWindow", "Sorted BY："))
        self.showForLabel.setText(_translate("NodeResultWindow", "Platform："))
        self.nameRadBtn.setText(_translate("NodeResultWindow", "name"))
        self.playsRadBtn.setText(_translate("NodeResultWindow", "plays"))
        self.commentsRadBtn.setText(_translate("NodeResultWindow", "comments"))
        self.durationRadBtn.setText(_translate("NodeResultWindow", "duration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NodeResultWindow = QtWidgets.QWidget()
    ui = Ui_NodeResultWindow()
    ui.setupUi(NodeResultWindow)
    NodeResultWindow.show()
    sys.exit(app.exec_())
