# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 180, 276, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.loginLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.loginLayout.setContentsMargins(0, 0, 0, 0)
        self.loginLayout.setObjectName("loginLayout")
        self.usernameLayout = QtWidgets.QHBoxLayout()
        self.usernameLayout.setObjectName("usernameLayout")
        self.userNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.usernameLayout.addWidget(self.userNameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.usernameLayout.addWidget(self.usernameLineEdit)
        self.loginLayout.addLayout(self.usernameLayout, 0, 0, 1, 1)
        self.passwdLayout = QtWidgets.QHBoxLayout()
        self.passwdLayout.setObjectName("passwdLayout")
        self.passwdLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passwdLabel.setObjectName("passwdLabel")
        self.passwdLayout.addWidget(self.passwdLabel)
        self.passwdLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwdLineEdit.setObjectName("passwdLineEdit")
        self.passwdLayout.addWidget(self.passwdLineEdit)
        self.loginLayout.addLayout(self.passwdLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signInBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.signInBtn.setObjectName("signInBtn")
        self.horizontalLayout.addWidget(self.signInBtn)
        self.signUpBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.signUpBtn.setObjectName("signUpBtn")
        self.horizontalLayout.addWidget(self.signUpBtn)
        self.loginLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        StartWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "StartWindow"))
        self.userNameLabel.setText(_translate("StartWindow", "username:"))
        self.passwdLabel.setText(_translate("StartWindow", "password:"))
        self.signInBtn.setText(_translate("StartWindow", "SignIn"))
        self.signUpBtn.setText(_translate("StartWindow", "SignUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartWindow = QtWidgets.QMainWindow()
    ui = Ui_StartWindow()
    ui.setupUi(StartWindow)
    StartWindow.show()
    sys.exit(app.exec_())
